data:
  seed: 0
  solver:
    _target_: src.simulators.solvers.get_solver
    name: rk4

  sim_time:
    _target_: src.simulators.types.SimTime
    t0: 0.0 # in seconds
    tn: 50.0  # in seconds (including validation time)
    eps: 0.05 #  Make sure to take the Shannon's theorem into account


  system:
    _target_: src.simulators.systems.Rossler
    num_samples: 10
    system_param:
      _target_: src.simulators.types.SysParam
      C: [ 0, 1, 0 ] # Observation matrix
      ObservableIndex: [ 1 ]
      system_coeff:
        a: 0.2
        b: 0.2
        c: 5.7
    sampler:
      _target_: src.simulators.sampler.get_sampler
      sampler_type: lhs
      seed: ${ data.seed }
      sample_space: [ [ -1,1 ],[ -1,1 ], [ -1,1 ] ]
#    p_noise:
#      _target_: src.simulators.noise.get_noise
#      noise_type: gaussian
#      mean: 0
#      std: 0.1
#    m_noise:
#      _target_: src.simulators.noise.get_noise
#      noise_type: gaussian
#      mean: 0
#      std: 0.1

