credentials: /media/yehias21/DATA/projects/KKL observer/hyperkkl/baselines/config/credentials.yaml
dirs:
  data: ${hydra:run.dir}
  logs: ${hydra:runtime.cwd}/logs
  models: ${hydra:runtime.cwd}/models

data:
  seed: 123
  solver: rk4
  data_gen_mode: backward sim
  PINN_sample_mode: split set
  sampler:
    name: lhs
    num_samples: 50
  sim_time:
    start_time: 0.0 # in seconds
    end_time: 50.0  # in seconds
    dt: 0.001 #  Make sure to take the Shannon's theorem into account
  system:
    name: duffing
  observer:
    z_size: 5
    e: 0.000001 #10e-6

models:

  forward_mapper:
    type: MLP
    update_method: full #backprop, delta, full
    input_size: 2
    output_size: 5
    hidden_dim: [100, 100, 100]
    activation: [relu, relu, relu]
    pretrained: False

  inverse_mapper:
    type: MLP
    update_method: backprop #backprop, delta, full
    input_size: 5
    output_size: 2
    hidden_dim: [100, 100, 100]
    activation: [relu, relu, relu]
    pretrained: False

  hypernetwork:
    shared: True
    encoder:
      type: MLP
      update_method: backprop
      input_size: 1
      output_size: 128
      hidden_sizes: [100, 100, 100]
      activation: [relu, relu, relu]
    decoder:
      method: lora #Full, chunked, lora
      rank_ratio: 0.5

trainer:
  method: supervised    #or unsupervised
  epochs: 15
  learning_rate: 0.001
  batch_size: 32
  lambda: 1
