# Lorenz Attractor System
name: lorenz
_target_: src.simulators.systems.Lorenz

state_dim: 3
output_dim: 1

observation:
  C: [0.0, 1.0, 0.0]
  observable_index: [1]

coefficients:
  sigma: 10.0
  rho: 28.0
  beta: 2.6667  # 8/3

ic_space: [[-1.0, 1.0], [-1.0, 1.0], [-1.0, 1.0]]

noise:
  process:
    _target_: src.simulators.noise.GaussianNoise
    mean: 0.0
    std: 0.05
  measurement:
    _target_: src.simulators.noise.GaussianNoise
    mean: 0.0
    std: 0.05
