# Van der Pol Oscillator
name: vdp
_target_: src.simulators.systems.VanDerPol

state_dim: 2
output_dim: 1

observation:
  C: [1.0, 0.0]
  observable_index: [0]

coefficients:
  mu: 1.0

ic_space: [[-1.0, 1.0], [-1.0, 1.0]]

noise:
  process:
    _target_: src.simulators.noise.GaussianNoise
    mean: 0.0
    std: 0.1
  measurement:
    _target_: src.simulators.noise.GaussianNoise
    mean: 0.0
    std: 0.1
